# sqlalchemy imports
from sqlalchemy import Column, create_engine, ForeignKey
from sqlalchemy import Integer, String, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker, backref

# other imports
import random
import string

# Initializations
Base = declarative_base()
secret_key = ''.join(random.choice(
    string.ascii_uppercase + string.digits) for x in xrange(32))


class User(Base):
    '''
    User table

    Columns:
        id (int): PK for the table
        username (string)
        picture (string): url for the picture
        email (string):
        password_hash (string): hashed password created by hash_password
    '''
    __tablename__ = 'user'

    id = Column(Integer, primary_key=True)
    username = Column(String(32), index=True, nullable=False)
    picture = Column(String)
    email = Column(String(100), nullable=False, unique=True)
    password_hash = Column(String(100), nullable=False)

    @property
    def serializeWithItems(self):
        '''
        Returns:
            object data in a serializable format with the list of items
        '''
        return {
            'id': self.id,
            'username': self.name,
            'email': self.email
        }

class Category(Base):
    '''
    Category table

    Columns:
        id (int): identifier for the category, autogenerated
        name (string): name of the category
        user_id (int): foreignkey refering to the user that created the
        user (User): RelationShip - user object created the category
        items (Item): RelationShip - list of items that belong to the category
    '''
    __tablename__ = 'category'

    id = Column(Integer, primary_key=True)
    name = Column(String(80), index=True, nullable=False)
    user_id = Column(Integer, ForeignKey('user.id'))

    user = relationship(User)

    @property
    def serializeWithItems(self):
        '''
        Returns:
            object data in a serializable format with the list of items
        '''
        return {
            'id': self.id,
            'name': self.name,
            'item': [item.serialize for item in self.items]
        }

    @property
    def serializeWithoutItems(self):
        '''
        Returns:
            object data in a serializable format without the list of items
        '''
        return {
            'id': self.id,
            'name': self.name
        }


class Item(Base):
    '''
    Item table

    Columns:
        id (int): identifier for the item, autogenerated
        title (string): name of the item
        description (text)
        category_id (int)
        user_id (int)
        category (Category): RelationShip - many-to-one relationship
        user (User): RelationShip - many-to-one relationship
    '''
    __tablename__ = 'item'

    id = Column(Integer, primary_key=True)
    title = Column(String(80), index=True, nullable=False)
    description = Column(Text)
    category_id = Column(Integer, ForeignKey('category.id'))
    user_id = Column(Integer, ForeignKey('user.id'))

    # use cascade='delete,all' to propagate the deletion of the category onto
    # its items
    category = relationship(
        Category,
        backref=backref('items', uselist=True, cascade='all, delete'))
    user = relationship(User)

    @property
    def serialize(self):
        '''
        Returns:
            object data in a serializable format
        '''
        return {
            'id': self.id,
            'title': self.title,
            'description': self.description,
            'category_id': self.category_id
        }


engine = create_engine('postgresql://catalog:udacity_linux_Fullstack@localhost/catalog')
Base.metadata.create_all(engine)
